# Generated by Django 4.2.13 on 2024-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('annotation_text', models.CharField(max_length=100)),
                ('annotation_type', models.CharField(max_length=100)),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
            ],
        ),
    ]
